# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tourney_stream_pb2 as tourney__stream__pb2


class StreamingArenaStub(object):
    """The "Clean" Service: Stateful and In-Memory
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Battle = channel.stream_stream(
                '/tourney.stream.StreamingArena/Battle',
                request_serializer=tourney__stream__pb2.ArenaMessage.SerializeToString,
                response_deserializer=tourney__stream__pb2.GameUpdate.FromString,
                )


class StreamingArenaServicer(object):
    """The "Clean" Service: Stateful and In-Memory
    """

    def Battle(self, request_iterator, context):
        """BiDi Streaming: The connection IS the match state.
        The Judge sends a "Pulse" (trigger), the Client sends a "Move".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingArenaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Battle': grpc.stream_stream_rpc_method_handler(
                    servicer.Battle,
                    request_deserializer=tourney__stream__pb2.ArenaMessage.FromString,
                    response_serializer=tourney__stream__pb2.GameUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tourney.stream.StreamingArena', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamingArena(object):
    """The "Clean" Service: Stateful and In-Memory
    """

    @staticmethod
    def Battle(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/tourney.stream.StreamingArena/Battle',
            tourney__stream__pb2.ArenaMessage.SerializeToString,
            tourney__stream__pb2.GameUpdate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
