# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tourney_unary.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tourney_unary.proto\x12\rtourney.unary\"D\n\x13RegistrationRequest\x12\x15\n\rlanguage_name\x18\x01 \x01(\t\x12\x16\n\x0eprng_algorithm\x18\x02 \x01(\t\"O\n\x14RegistrationResponse\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x15\n\ropponent_name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"C\n\x0bMoveRequest\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x0c\n\x04move\x18\x03 \x01(\x05\"\x1e\n\x0cMoveResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"7\n\rResultRequest\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\"H\n\x0eResultResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\ropponent_move\x18\x02 \x01(\x05\x12\x0f\n\x07outcome\x18\x03 \x01(\t2\xf9\x01\n\nUnaryArena\x12S\n\x08Register\x12\".tourney.unary.RegistrationRequest\x1a#.tourney.unary.RegistrationResponse\x12\x45\n\nSubmitMove\x12\x1a.tourney.unary.MoveRequest\x1a\x1b.tourney.unary.MoveResponse\x12O\n\x10\x43heckRoundResult\x12\x1c.tourney.unary.ResultRequest\x1a\x1d.tourney.unary.ResultResponseB\x1d\n\x19\x63om.rickert.tourney.unaryP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tourney_unary_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.rickert.tourney.unaryP\001'
  _globals['_REGISTRATIONREQUEST']._serialized_start=38
  _globals['_REGISTRATIONREQUEST']._serialized_end=106
  _globals['_REGISTRATIONRESPONSE']._serialized_start=108
  _globals['_REGISTRATIONRESPONSE']._serialized_end=187
  _globals['_MOVEREQUEST']._serialized_start=189
  _globals['_MOVEREQUEST']._serialized_end=256
  _globals['_MOVERESPONSE']._serialized_start=258
  _globals['_MOVERESPONSE']._serialized_end=288
  _globals['_RESULTREQUEST']._serialized_start=290
  _globals['_RESULTREQUEST']._serialized_end=345
  _globals['_RESULTRESPONSE']._serialized_start=347
  _globals['_RESULTRESPONSE']._serialized_end=419
  _globals['_UNARYARENA']._serialized_start=422
  _globals['_UNARYARENA']._serialized_end=671
# @@protoc_insertion_point(module_scope)
