# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tourney_stream.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14tourney_stream.proto\x12\x0etourney.stream\"o\n\x0c\x41renaMessage\x12.\n\thandshake\x18\x01 \x01(\x0b\x32\x19.tourney.stream.HandshakeH\x00\x12$\n\x04move\x18\x02 \x01(\x0b\x32\x14.tourney.stream.MoveH\x00\x42\t\n\x07payload\":\n\tHandshake\x12\x15\n\rlanguage_name\x18\x01 \x01(\t\x12\x16\n\x0eprng_algorithm\x18\x02 \x01(\t\"\x14\n\x04Move\x12\x0c\n\x04move\x18\x01 \x01(\x05\"\x88\x01\n\nGameUpdate\x12\x10\n\x06status\x18\x01 \x01(\tH\x00\x12.\n\x07trigger\x18\x02 \x01(\x0b\x32\x1b.tourney.stream.RequestMoveH\x00\x12-\n\x06result\x18\x03 \x01(\x0b\x32\x1b.tourney.stream.RoundResultH\x00\x42\t\n\x07payload\"\x1f\n\x0bRequestMove\x12\x10\n\x08round_id\x18\x01 \x01(\x05\"G\n\x0bRoundResult\x12\x10\n\x08round_id\x18\x01 \x01(\x05\x12\x15\n\ropponent_move\x18\x02 \x01(\x05\x12\x0f\n\x07outcome\x18\x03 \x01(\t2X\n\x0eStreamingArena\x12\x46\n\x06\x42\x61ttle\x12\x1c.tourney.stream.ArenaMessage\x1a\x1a.tourney.stream.GameUpdate(\x01\x30\x01\x42\x1e\n\x1a\x63om.rickert.tourney.streamP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tourney_stream_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.rickert.tourney.streamP\001'
  _globals['_ARENAMESSAGE']._serialized_start=40
  _globals['_ARENAMESSAGE']._serialized_end=151
  _globals['_HANDSHAKE']._serialized_start=153
  _globals['_HANDSHAKE']._serialized_end=211
  _globals['_MOVE']._serialized_start=213
  _globals['_MOVE']._serialized_end=233
  _globals['_GAMEUPDATE']._serialized_start=236
  _globals['_GAMEUPDATE']._serialized_end=372
  _globals['_REQUESTMOVE']._serialized_start=374
  _globals['_REQUESTMOVE']._serialized_end=405
  _globals['_ROUNDRESULT']._serialized_start=407
  _globals['_ROUNDRESULT']._serialized_end=478
  _globals['_STREAMINGARENA']._serialized_start=480
  _globals['_STREAMINGARENA']._serialized_end=568
# @@protoc_insertion_point(module_scope)
