# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tourney_unary_pb2 as tourney__unary__pb2


class UnaryArenaStub(object):
    """The "Heavy" Service: Stateless and Database-Dependent
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/tourney.unary.UnaryArena/Register',
                request_serializer=tourney__unary__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=tourney__unary__pb2.RegistrationResponse.FromString,
                )
        self.SubmitMove = channel.unary_unary(
                '/tourney.unary.UnaryArena/SubmitMove',
                request_serializer=tourney__unary__pb2.MoveRequest.SerializeToString,
                response_deserializer=tourney__unary__pb2.MoveResponse.FromString,
                )
        self.CheckRoundResult = channel.unary_unary(
                '/tourney.unary.UnaryArena/CheckRoundResult',
                request_serializer=tourney__unary__pb2.ResultRequest.SerializeToString,
                response_deserializer=tourney__unary__pb2.ResultResponse.FromString,
                )


class UnaryArenaServicer(object):
    """The "Heavy" Service: Stateless and Database-Dependent
    """

    def Register(self, request, context):
        """Step 1: Client registers to play. Returns a match_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitMove(self, request, context):
        """Step 2: Client submits a move. 
        The Server will likely return "WAITING" if the opponent hasn't moved.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckRoundResult(self, request, context):
        """Step 3: Client must POLL this repeatedly to see if they won the round.
        This is the "Latency Tax."
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnaryArenaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=tourney__unary__pb2.RegistrationRequest.FromString,
                    response_serializer=tourney__unary__pb2.RegistrationResponse.SerializeToString,
            ),
            'SubmitMove': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMove,
                    request_deserializer=tourney__unary__pb2.MoveRequest.FromString,
                    response_serializer=tourney__unary__pb2.MoveResponse.SerializeToString,
            ),
            'CheckRoundResult': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckRoundResult,
                    request_deserializer=tourney__unary__pb2.ResultRequest.FromString,
                    response_serializer=tourney__unary__pb2.ResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tourney.unary.UnaryArena', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnaryArena(object):
    """The "Heavy" Service: Stateless and Database-Dependent
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tourney.unary.UnaryArena/Register',
            tourney__unary__pb2.RegistrationRequest.SerializeToString,
            tourney__unary__pb2.RegistrationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tourney.unary.UnaryArena/SubmitMove',
            tourney__unary__pb2.MoveRequest.SerializeToString,
            tourney__unary__pb2.MoveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckRoundResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tourney.unary.UnaryArena/CheckRoundResult',
            tourney__unary__pb2.ResultRequest.SerializeToString,
            tourney__unary__pb2.ResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
