// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: tourney_stream.proto

package tourney_stream

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamingArena_Battle_FullMethodName = "/tourney.stream.StreamingArena/Battle"
)

// StreamingArenaClient is the client API for StreamingArena service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The "Clean" Service: Stateful and In-Memory
type StreamingArenaClient interface {
	// BiDi Streaming: The connection IS the match state.
	// The Judge sends a "Pulse" (trigger), the Client sends a "Move".
	Battle(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ArenaMessage, GameUpdate], error)
}

type streamingArenaClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamingArenaClient(cc grpc.ClientConnInterface) StreamingArenaClient {
	return &streamingArenaClient{cc}
}

func (c *streamingArenaClient) Battle(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ArenaMessage, GameUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamingArena_ServiceDesc.Streams[0], StreamingArena_Battle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ArenaMessage, GameUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingArena_BattleClient = grpc.BidiStreamingClient[ArenaMessage, GameUpdate]

// StreamingArenaServer is the server API for StreamingArena service.
// All implementations must embed UnimplementedStreamingArenaServer
// for forward compatibility.
//
// The "Clean" Service: Stateful and In-Memory
type StreamingArenaServer interface {
	// BiDi Streaming: The connection IS the match state.
	// The Judge sends a "Pulse" (trigger), the Client sends a "Move".
	Battle(grpc.BidiStreamingServer[ArenaMessage, GameUpdate]) error
	mustEmbedUnimplementedStreamingArenaServer()
}

// UnimplementedStreamingArenaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamingArenaServer struct{}

func (UnimplementedStreamingArenaServer) Battle(grpc.BidiStreamingServer[ArenaMessage, GameUpdate]) error {
	return status.Error(codes.Unimplemented, "method Battle not implemented")
}
func (UnimplementedStreamingArenaServer) mustEmbedUnimplementedStreamingArenaServer() {}
func (UnimplementedStreamingArenaServer) testEmbeddedByValue()                        {}

// UnsafeStreamingArenaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamingArenaServer will
// result in compilation errors.
type UnsafeStreamingArenaServer interface {
	mustEmbedUnimplementedStreamingArenaServer()
}

func RegisterStreamingArenaServer(s grpc.ServiceRegistrar, srv StreamingArenaServer) {
	// If the following call panics, it indicates UnimplementedStreamingArenaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamingArena_ServiceDesc, srv)
}

func _StreamingArena_Battle_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamingArenaServer).Battle(&grpc.GenericServerStream[ArenaMessage, GameUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamingArena_BattleServer = grpc.BidiStreamingServer[ArenaMessage, GameUpdate]

// StreamingArena_ServiceDesc is the grpc.ServiceDesc for StreamingArena service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamingArena_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tourney.stream.StreamingArena",
	HandlerType: (*StreamingArenaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Battle",
			Handler:       _StreamingArena_Battle_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tourney_stream.proto",
}
