// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: tourney_stream.proto

package tourney_stream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One message type to rule them all (Polymorphism via Oneof)
type ArenaMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ArenaMessage_Handshake
	//	*ArenaMessage_Move
	Payload       isArenaMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArenaMessage) Reset() {
	*x = ArenaMessage{}
	mi := &file_tourney_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArenaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaMessage) ProtoMessage() {}

func (x *ArenaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaMessage.ProtoReflect.Descriptor instead.
func (*ArenaMessage) Descriptor() ([]byte, []int) {
	return file_tourney_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ArenaMessage) GetPayload() isArenaMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ArenaMessage) GetHandshake() *Handshake {
	if x != nil {
		if x, ok := x.Payload.(*ArenaMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *ArenaMessage) GetMove() *Move {
	if x != nil {
		if x, ok := x.Payload.(*ArenaMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

type isArenaMessage_Payload interface {
	isArenaMessage_Payload()
}

type ArenaMessage_Handshake struct {
	Handshake *Handshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type ArenaMessage_Move struct {
	Move *Move `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

func (*ArenaMessage_Handshake) isArenaMessage_Payload() {}

func (*ArenaMessage_Move) isArenaMessage_Payload() {}

type Handshake struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageName  string                 `protobuf:"bytes,1,opt,name=language_name,json=languageName,proto3" json:"language_name,omitempty"`
	PrngAlgorithm string                 `protobuf:"bytes,2,opt,name=prng_algorithm,json=prngAlgorithm,proto3" json:"prng_algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Handshake) Reset() {
	*x = Handshake{}
	mi := &file_tourney_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Handshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Handshake) ProtoMessage() {}

func (x *Handshake) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Handshake.ProtoReflect.Descriptor instead.
func (*Handshake) Descriptor() ([]byte, []int) {
	return file_tourney_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Handshake) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *Handshake) GetPrngAlgorithm() string {
	if x != nil {
		return x.PrngAlgorithm
	}
	return ""
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Move          int32                  `protobuf:"varint,1,opt,name=move,proto3" json:"move,omitempty"` // 0=Rock, 1=Paper, 2=Scissors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_tourney_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_tourney_stream_proto_rawDescGZIP(), []int{2}
}

func (x *Move) GetMove() int32 {
	if x != nil {
		return x.Move
	}
	return 0
}

// Server responses
type GameUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GameUpdate_Status
	//	*GameUpdate_Trigger
	//	*GameUpdate_Result
	Payload       isGameUpdate_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameUpdate) Reset() {
	*x = GameUpdate{}
	mi := &file_tourney_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdate) ProtoMessage() {}

func (x *GameUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdate.ProtoReflect.Descriptor instead.
func (*GameUpdate) Descriptor() ([]byte, []int) {
	return file_tourney_stream_proto_rawDescGZIP(), []int{3}
}

func (x *GameUpdate) GetPayload() isGameUpdate_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GameUpdate) GetStatus() string {
	if x != nil {
		if x, ok := x.Payload.(*GameUpdate_Status); ok {
			return x.Status
		}
	}
	return ""
}

func (x *GameUpdate) GetTrigger() *RequestMove {
	if x != nil {
		if x, ok := x.Payload.(*GameUpdate_Trigger); ok {
			return x.Trigger
		}
	}
	return nil
}

func (x *GameUpdate) GetResult() *RoundResult {
	if x != nil {
		if x, ok := x.Payload.(*GameUpdate_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isGameUpdate_Payload interface {
	isGameUpdate_Payload()
}

type GameUpdate_Status struct {
	Status string `protobuf:"bytes,1,opt,name=status,proto3,oneof"` // "CONNECTED", "OPPONENT_FOUND"
}

type GameUpdate_Trigger struct {
	Trigger *RequestMove `protobuf:"bytes,2,opt,name=trigger,proto3,oneof"` // The "Pulse" asking for a move
}

type GameUpdate_Result struct {
	Result *RoundResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"` // Immediate feedback
}

func (*GameUpdate_Status) isGameUpdate_Payload() {}

func (*GameUpdate_Trigger) isGameUpdate_Payload() {}

func (*GameUpdate_Result) isGameUpdate_Payload() {}

type RequestMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       int32                  `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMove) Reset() {
	*x = RequestMove{}
	mi := &file_tourney_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMove) ProtoMessage() {}

func (x *RequestMove) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMove.ProtoReflect.Descriptor instead.
func (*RequestMove) Descriptor() ([]byte, []int) {
	return file_tourney_stream_proto_rawDescGZIP(), []int{4}
}

func (x *RequestMove) GetRoundId() int32 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

type RoundResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoundId       int32                  `protobuf:"varint,1,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	OpponentMove  int32                  `protobuf:"varint,2,opt,name=opponent_move,json=opponentMove,proto3" json:"opponent_move,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"` // "WIN", "LOSS", "TIE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	mi := &file_tourney_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_tourney_stream_proto_rawDescGZIP(), []int{5}
}

func (x *RoundResult) GetRoundId() int32 {
	if x != nil {
		return x.RoundId
	}
	return 0
}

func (x *RoundResult) GetOpponentMove() int32 {
	if x != nil {
		return x.OpponentMove
	}
	return 0
}

func (x *RoundResult) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

var File_tourney_stream_proto protoreflect.FileDescriptor

const file_tourney_stream_proto_rawDesc = "" +
	"\n" +
	"\x14tourney_stream.proto\x12\x0etourney.stream\"\x80\x01\n" +
	"\fArenaMessage\x129\n" +
	"\thandshake\x18\x01 \x01(\v2\x19.tourney.stream.HandshakeH\x00R\thandshake\x12*\n" +
	"\x04move\x18\x02 \x01(\v2\x14.tourney.stream.MoveH\x00R\x04moveB\t\n" +
	"\apayload\"W\n" +
	"\tHandshake\x12#\n" +
	"\rlanguage_name\x18\x01 \x01(\tR\flanguageName\x12%\n" +
	"\x0eprng_algorithm\x18\x02 \x01(\tR\rprngAlgorithm\"\x1a\n" +
	"\x04Move\x12\x12\n" +
	"\x04move\x18\x01 \x01(\x05R\x04move\"\xa1\x01\n" +
	"\n" +
	"GameUpdate\x12\x18\n" +
	"\x06status\x18\x01 \x01(\tH\x00R\x06status\x127\n" +
	"\atrigger\x18\x02 \x01(\v2\x1b.tourney.stream.RequestMoveH\x00R\atrigger\x125\n" +
	"\x06result\x18\x03 \x01(\v2\x1b.tourney.stream.RoundResultH\x00R\x06resultB\t\n" +
	"\apayload\"(\n" +
	"\vRequestMove\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\x05R\aroundId\"g\n" +
	"\vRoundResult\x12\x19\n" +
	"\bround_id\x18\x01 \x01(\x05R\aroundId\x12#\n" +
	"\ropponent_move\x18\x02 \x01(\x05R\fopponentMove\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome2X\n" +
	"\x0eStreamingArena\x12F\n" +
	"\x06Battle\x12\x1c.tourney.stream.ArenaMessage\x1a\x1a.tourney.stream.GameUpdate(\x010\x01Bi\n" +
	"\x1acom.rickert.tourney.streamP\x01ZIgithub.com/ai-pipestream/paper-rock-scissors/clients/go/pb/tourney_streamb\x06proto3"

var (
	file_tourney_stream_proto_rawDescOnce sync.Once
	file_tourney_stream_proto_rawDescData []byte
)

func file_tourney_stream_proto_rawDescGZIP() []byte {
	file_tourney_stream_proto_rawDescOnce.Do(func() {
		file_tourney_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tourney_stream_proto_rawDesc), len(file_tourney_stream_proto_rawDesc)))
	})
	return file_tourney_stream_proto_rawDescData
}

var file_tourney_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tourney_stream_proto_goTypes = []any{
	(*ArenaMessage)(nil), // 0: tourney.stream.ArenaMessage
	(*Handshake)(nil),    // 1: tourney.stream.Handshake
	(*Move)(nil),         // 2: tourney.stream.Move
	(*GameUpdate)(nil),   // 3: tourney.stream.GameUpdate
	(*RequestMove)(nil),  // 4: tourney.stream.RequestMove
	(*RoundResult)(nil),  // 5: tourney.stream.RoundResult
}
var file_tourney_stream_proto_depIdxs = []int32{
	1, // 0: tourney.stream.ArenaMessage.handshake:type_name -> tourney.stream.Handshake
	2, // 1: tourney.stream.ArenaMessage.move:type_name -> tourney.stream.Move
	4, // 2: tourney.stream.GameUpdate.trigger:type_name -> tourney.stream.RequestMove
	5, // 3: tourney.stream.GameUpdate.result:type_name -> tourney.stream.RoundResult
	0, // 4: tourney.stream.StreamingArena.Battle:input_type -> tourney.stream.ArenaMessage
	3, // 5: tourney.stream.StreamingArena.Battle:output_type -> tourney.stream.GameUpdate
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_tourney_stream_proto_init() }
func file_tourney_stream_proto_init() {
	if File_tourney_stream_proto != nil {
		return
	}
	file_tourney_stream_proto_msgTypes[0].OneofWrappers = []any{
		(*ArenaMessage_Handshake)(nil),
		(*ArenaMessage_Move)(nil),
	}
	file_tourney_stream_proto_msgTypes[3].OneofWrappers = []any{
		(*GameUpdate_Status)(nil),
		(*GameUpdate_Trigger)(nil),
		(*GameUpdate_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tourney_stream_proto_rawDesc), len(file_tourney_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tourney_stream_proto_goTypes,
		DependencyIndexes: file_tourney_stream_proto_depIdxs,
		MessageInfos:      file_tourney_stream_proto_msgTypes,
	}.Build()
	File_tourney_stream_proto = out.File
	file_tourney_stream_proto_goTypes = nil
	file_tourney_stream_proto_depIdxs = nil
}
