// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: tourney_unary.proto

package tourney_unary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LanguageName  string                 `protobuf:"bytes,1,opt,name=language_name,json=languageName,proto3" json:"language_name,omitempty"`    // e.g., "Java-21", "Python-3.11"
	PrngAlgorithm string                 `protobuf:"bytes,2,opt,name=prng_algorithm,json=prngAlgorithm,proto3" json:"prng_algorithm,omitempty"` // e.g., "L64X128MixRandom"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_tourney_unary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_unary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_tourney_unary_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *RegistrationRequest) GetPrngAlgorithm() string {
	if x != nil {
		return x.PrngAlgorithm
	}
	return ""
}

type RegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"` // The "Context Key"
	OpponentName  string                 `protobuf:"bytes,2,opt,name=opponent_name,json=opponentName,proto3" json:"opponent_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "WAITING_FOR_OPPONENT" or "READY"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationResponse) Reset() {
	*x = RegistrationResponse{}
	mi := &file_tourney_unary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationResponse) ProtoMessage() {}

func (x *RegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_unary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationResponse.ProtoReflect.Descriptor instead.
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return file_tourney_unary_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *RegistrationResponse) GetOpponentName() string {
	if x != nil {
		return x.OpponentName
	}
	return ""
}

func (x *RegistrationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`              // REQUIRED: Context lookup
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"` // REQUIRED: State sync
	Move          int32                  `protobuf:"varint,3,opt,name=move,proto3" json:"move,omitempty"`                                  // 0=Rock, 1=Paper, 2=Scissors
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_tourney_unary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_unary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_tourney_unary_proto_rawDescGZIP(), []int{2}
}

func (x *MoveRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MoveRequest) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

func (x *MoveRequest) GetMove() int32 {
	if x != nil {
		return x.Move
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ACCEPTED", "INVALID_TURN", "GAME_OVER"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_tourney_unary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_unary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_tourney_unary_proto_rawDescGZIP(), []int{3}
}

func (x *MoveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=round_number,json=roundNumber,proto3" json:"round_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_tourney_unary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_unary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_tourney_unary_proto_rawDescGZIP(), []int{4}
}

func (x *ResultRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *ResultRequest) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "PENDING", "COMPLETE"
	OpponentMove  int32                  `protobuf:"varint,2,opt,name=opponent_move,json=opponentMove,proto3" json:"opponent_move,omitempty"`
	Outcome       string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"` // "WIN", "LOSS", "TIE"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_tourney_unary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tourney_unary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_tourney_unary_proto_rawDescGZIP(), []int{5}
}

func (x *ResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResultResponse) GetOpponentMove() int32 {
	if x != nil {
		return x.OpponentMove
	}
	return 0
}

func (x *ResultResponse) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

var File_tourney_unary_proto protoreflect.FileDescriptor

const file_tourney_unary_proto_rawDesc = "" +
	"\n" +
	"\x13tourney_unary.proto\x12\rtourney.unary\"a\n" +
	"\x13RegistrationRequest\x12#\n" +
	"\rlanguage_name\x18\x01 \x01(\tR\flanguageName\x12%\n" +
	"\x0eprng_algorithm\x18\x02 \x01(\tR\rprngAlgorithm\"n\n" +
	"\x14RegistrationResponse\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12#\n" +
	"\ropponent_name\x18\x02 \x01(\tR\fopponentName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"_\n" +
	"\vMoveRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\x12\x12\n" +
	"\x04move\x18\x03 \x01(\x05R\x04move\"&\n" +
	"\fMoveResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"M\n" +
	"\rResultRequest\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12!\n" +
	"\fround_number\x18\x02 \x01(\x05R\vroundNumber\"g\n" +
	"\x0eResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\ropponent_move\x18\x02 \x01(\x05R\fopponentMove\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome2\xf9\x01\n" +
	"\n" +
	"UnaryArena\x12S\n" +
	"\bRegister\x12\".tourney.unary.RegistrationRequest\x1a#.tourney.unary.RegistrationResponse\x12E\n" +
	"\n" +
	"SubmitMove\x12\x1a.tourney.unary.MoveRequest\x1a\x1b.tourney.unary.MoveResponse\x12O\n" +
	"\x10CheckRoundResult\x12\x1c.tourney.unary.ResultRequest\x1a\x1d.tourney.unary.ResultResponseBg\n" +
	"\x19com.rickert.tourney.unaryP\x01ZHgithub.com/ai-pipestream/paper-rock-scissors/clients/go/pb/tourney_unaryb\x06proto3"

var (
	file_tourney_unary_proto_rawDescOnce sync.Once
	file_tourney_unary_proto_rawDescData []byte
)

func file_tourney_unary_proto_rawDescGZIP() []byte {
	file_tourney_unary_proto_rawDescOnce.Do(func() {
		file_tourney_unary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tourney_unary_proto_rawDesc), len(file_tourney_unary_proto_rawDesc)))
	})
	return file_tourney_unary_proto_rawDescData
}

var file_tourney_unary_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tourney_unary_proto_goTypes = []any{
	(*RegistrationRequest)(nil),  // 0: tourney.unary.RegistrationRequest
	(*RegistrationResponse)(nil), // 1: tourney.unary.RegistrationResponse
	(*MoveRequest)(nil),          // 2: tourney.unary.MoveRequest
	(*MoveResponse)(nil),         // 3: tourney.unary.MoveResponse
	(*ResultRequest)(nil),        // 4: tourney.unary.ResultRequest
	(*ResultResponse)(nil),       // 5: tourney.unary.ResultResponse
}
var file_tourney_unary_proto_depIdxs = []int32{
	0, // 0: tourney.unary.UnaryArena.Register:input_type -> tourney.unary.RegistrationRequest
	2, // 1: tourney.unary.UnaryArena.SubmitMove:input_type -> tourney.unary.MoveRequest
	4, // 2: tourney.unary.UnaryArena.CheckRoundResult:input_type -> tourney.unary.ResultRequest
	1, // 3: tourney.unary.UnaryArena.Register:output_type -> tourney.unary.RegistrationResponse
	3, // 4: tourney.unary.UnaryArena.SubmitMove:output_type -> tourney.unary.MoveResponse
	5, // 5: tourney.unary.UnaryArena.CheckRoundResult:output_type -> tourney.unary.ResultResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tourney_unary_proto_init() }
func file_tourney_unary_proto_init() {
	if File_tourney_unary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tourney_unary_proto_rawDesc), len(file_tourney_unary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tourney_unary_proto_goTypes,
		DependencyIndexes: file_tourney_unary_proto_depIdxs,
		MessageInfos:      file_tourney_unary_proto_msgTypes,
	}.Build()
	File_tourney_unary_proto = out.File
	file_tourney_unary_proto_goTypes = nil
	file_tourney_unary_proto_depIdxs = nil
}
