// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: tourney_unary.proto

package tourney_unary

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UnaryArena_Register_FullMethodName         = "/tourney.unary.UnaryArena/Register"
	UnaryArena_SubmitMove_FullMethodName       = "/tourney.unary.UnaryArena/SubmitMove"
	UnaryArena_CheckRoundResult_FullMethodName = "/tourney.unary.UnaryArena/CheckRoundResult"
)

// UnaryArenaClient is the client API for UnaryArena service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The "Heavy" Service: Stateless and Database-Dependent
type UnaryArenaClient interface {
	// Step 1: Client registers to play. Returns a match_id.
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
	// Step 2: Client submits a move.
	// The Server will likely return "WAITING" if the opponent hasn't moved.
	SubmitMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	// Step 3: Client must POLL this repeatedly to see if they won the round.
	// This is the "Latency Tax."
	CheckRoundResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error)
}

type unaryArenaClient struct {
	cc grpc.ClientConnInterface
}

func NewUnaryArenaClient(cc grpc.ClientConnInterface) UnaryArenaClient {
	return &unaryArenaClient{cc}
}

func (c *unaryArenaClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, UnaryArena_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unaryArenaClient) SubmitMove(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, UnaryArena_SubmitMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *unaryArenaClient) CheckRoundResult(ctx context.Context, in *ResultRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, UnaryArena_CheckRoundResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnaryArenaServer is the server API for UnaryArena service.
// All implementations must embed UnimplementedUnaryArenaServer
// for forward compatibility.
//
// The "Heavy" Service: Stateless and Database-Dependent
type UnaryArenaServer interface {
	// Step 1: Client registers to play. Returns a match_id.
	Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
	// Step 2: Client submits a move.
	// The Server will likely return "WAITING" if the opponent hasn't moved.
	SubmitMove(context.Context, *MoveRequest) (*MoveResponse, error)
	// Step 3: Client must POLL this repeatedly to see if they won the round.
	// This is the "Latency Tax."
	CheckRoundResult(context.Context, *ResultRequest) (*ResultResponse, error)
	mustEmbedUnimplementedUnaryArenaServer()
}

// UnimplementedUnaryArenaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUnaryArenaServer struct{}

func (UnimplementedUnaryArenaServer) Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUnaryArenaServer) SubmitMove(context.Context, *MoveRequest) (*MoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitMove not implemented")
}
func (UnimplementedUnaryArenaServer) CheckRoundResult(context.Context, *ResultRequest) (*ResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckRoundResult not implemented")
}
func (UnimplementedUnaryArenaServer) mustEmbedUnimplementedUnaryArenaServer() {}
func (UnimplementedUnaryArenaServer) testEmbeddedByValue()                    {}

// UnsafeUnaryArenaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnaryArenaServer will
// result in compilation errors.
type UnsafeUnaryArenaServer interface {
	mustEmbedUnimplementedUnaryArenaServer()
}

func RegisterUnaryArenaServer(s grpc.ServiceRegistrar, srv UnaryArenaServer) {
	// If the following call panics, it indicates UnimplementedUnaryArenaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UnaryArena_ServiceDesc, srv)
}

func _UnaryArena_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryArenaServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnaryArena_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryArenaServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnaryArena_SubmitMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryArenaServer).SubmitMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnaryArena_SubmitMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryArenaServer).SubmitMove(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UnaryArena_CheckRoundResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryArenaServer).CheckRoundResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UnaryArena_CheckRoundResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryArenaServer).CheckRoundResult(ctx, req.(*ResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UnaryArena_ServiceDesc is the grpc.ServiceDesc for UnaryArena service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnaryArena_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tourney.unary.UnaryArena",
	HandlerType: (*UnaryArenaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UnaryArena_Register_Handler,
		},
		{
			MethodName: "SubmitMove",
			Handler:    _UnaryArena_SubmitMove_Handler,
		},
		{
			MethodName: "CheckRoundResult",
			Handler:    _UnaryArena_CheckRoundResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tourney_unary.proto",
}
